# Generated by Django 6.0.2 on 2026-03-27 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('quality', 'Quality Grading'), ('demand', 'Demand Forecasting')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.JSONField()),
                ('prediction', models.JSONField()),
                ('user_override', models.BooleanField(default=False)),
                ('override_value', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service_type', 'timestamp'], name='ai_logs_aii_service_d44ee2_idx'), models.Index(fields=['user', 'timestamp'], name='ai_logs_aii_user_id_d43a12_idx'), models.Index(fields=['user_override'], name='ai_logs_aii_user_ov_1318f3_idx')],
            },
        ),
    ]
