# Generated by Django 6.0.2 on 2026-04-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_tracking_number_orderitem_is_packed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time_slot', models.CharField(choices=[('morning', 'Morning (8am–12pm)'), ('afternoon', 'Afternoon (12pm–5pm)'), ('evening', 'Evening (5pm–8pm)')], max_length=20)),
                ('pickup_address', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('collected', 'Collected'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='scheduled', max_length=20)),
                ('driver_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
        ),
    ]
