# Generated by Django 6.0.2 on 2026-05-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='scheduled_time_slot',
        ),
    ]
