# Generated by Django 6.0.2 on 2026-05-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_delivery_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_address',
        ),
    ]
