# Generated by Django 6.0.2 on 2026-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_delivery_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='producer_ready_at',
            field=models.DateTimeField(blank=True, help_text='When the producer marked their items ready for collection', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
