# Generated by Django 6.0.2 on 2026-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
