# Generated by Django 6.0.2 on 2026-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('producer', 'Producer'), ('logistics', 'Logistics')], default='customer', max_length=20),
        ),
    ]
