# Generated by Django 6.0.2 on 2026-04-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favouriteproducer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avoided_allergens',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
