# Generated by Django 6.0.2 on 2026-04-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
        ('accounts', '0004_customuser_avoided_allergens'),
    ]

    operations = [
    ]
