# Generated by Django 6.0.2 on 2026-02-26 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('preserves', 'Preserves'), ('seasonal', 'Seasonal Specialities')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('allergen_info', models.TextField(blank=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('best_before_date', models.DateField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
