# Generated by Django 6.0.2 on 2026-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_product_quality_assessed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('preserves', 'Preserves'), ('seasonal', 'Seasonal Specialities')], max_length=20),
        ),
    ]
