# Generated by Django 6.0.2 on 2026-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_surplus_product_surplus_discount_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Show low-stock warning when stock drops to this level or below. Set to 0 to disable.'),
        ),
    ]
