# Generated by Django 6.0.2 on 2026-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alerted',
            field=models.BooleanField(default=False, editable=False, help_text="Internal: tracks whether we've already sent the alert for the current low-stock state."),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_email_alerts',
            field=models.BooleanField(default=False, help_text="Email me when this product's stock drops to or below the threshold."),
        ),
    ]
